repo_id = "EIPs"

[production]
repository = "https://github.com/ethereum/EIPs.git"
base_url = "https://eips.ethereum.org/"

[staging]
repository = "https://github.com/eips-wg/EIPs.git"
base_url = "https://eips-wg.github.io/EIPs/"

[siblings.ERCs.production]
repository = "https://github.com/ethereum/ERCs.git"
base_url = "https://ercs.ethereum.org/"

[siblings.ERCs.staging]
repository = "https://github.com/eips-wg/ERCs.git"
base_url = "https://eips-wg.github.io/ERCs/"
